const textTermsAndConditions = `Please read and agree to these terms (the “Consent & Authorization”) to enroll in the program support initiative (the “Program”) by Sentrex Health Solutions Inc., Sentrex Pharmacy Group Inc., and its other subsidiaries, affiliates and subcontractors (collectively, “Sentrex”).
 
I acknowledge, understand and agree to the following and would like to enroll in the Program to receive all services offered by the Program in order to best manage my care.
 
The Program is provided by Sentrex. Sentrex offers certain patient services which may include, as applicable, insurance reimbursement assistance, financial support, diagnostic testing coordination, vaccination support and pharmacy services. I understand that my Personal and Health Information may be shared with those employees of Sentrex as needed to provide the services to me, and that such employees are bound by Applicable Law.
 
Sentrex is committed to protecting patient confidentiality and patient health information, including, without limitation, personal information (name, address, contact details, date of birth, financial information) and health information (medical history and conditions, health insurance) (collectively, “Personal and Health Information”), in accordance with all applicable laws, including the Personal Information Protection and Electronic Documents Act (Canada)) and the Personal  Information Protection Act (B.C.) (“Applicable Law”).
 
I acknowledge, understand and agree to the following:
 
By signing this Consent & Authorization, I consent to a representative of Sentrex enrolling me into a manufacturer patient support program that may be managed by a third-party provider, whereby my Personal and Health Information may be shared. I understand that on a case-by-case basis, my medication and services may be supported by the manufacturer patient support program (the “PSP”) that is run by Sentrex, and that I may be able to receive free of charge and/or financial assistance for my medication and associated services while my prescription coverage is being determined by my provincial and/or private plan, or where my coverage has reached the maximum amount allowable, and the manufacturer PSP is supplementing my coverage. I hereby authorize Sentrex to collaborate and manage the transfer of my prescription to the PSP pharmacy for benefit support when needed.
 
Sentrex will collect, use, disclose and/or store my Personal and Health Information via the Program including questionnaires, interview questions or other information gathering processes, electronic or otherwise (the “Authorized Use”), for the purpose of providing the services, monitoring and improving the Program, reporting adverse events, and modifying and improving its services more generally, or as may be required by Applicable Law. My Personal and Health Information may be collected from me and/or disclosed to my physicians, nurses, pharmacists, insurance providers, governmental authorities, and other such sources as may be required to provide the services and allowable by Applicable Law.
 
Provided my name and other identifying details are removed, I consent to the disclosure and sharing of my Personal and Health Information within Sentrex and with third parties and governmental authorities, including by way of general publication, as permitted by Applicable Law. The Program may contact me by telephone or electronic mail using the contact information I have provided above for the purposes of delivering the PSP only.
 
My insurance provider may disclose my insurance coverage information to the Program, and I consent to the use by the Program of such information for the purpose of verifying coverage and otherwise arranging for reimbursement for the product/s.
 
I acknowledge that that collection, use, disclosure and storage of my Personal and Health Information, and my consent given herein, are subject to and in accordance with Sentrex’s privacy policy, a copy of which has been made available at http://sentrex.com/ (the “Privacy Policy”). I acknowledge that I have read the Privacy Policy and the above provisions of this Consent & Authorization, have understood them in their entirety, and have been given the opportunity to ask questions. I acknowledge that if I have any further questions, or wish to withdraw my consent or make changes to my Personal and Health Information, I may contact Sentrex at: Sentrex Health Solutions Inc., Attn: Privacy Officer, 120 Valleywood Drive,  Markham, Ontario, L3R 6A7, Email: privacy@sentrex.com.
`

export default textTermsAndConditions